### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory

### ISSUE THREAD

**Issue by IbnNacer** [linuxscout/sarf#3]
As-salâmu 'alaykum

This software really looks great but unfortunately, despite all my efforts, it does not work !
I use Eclipse and I still have errors:

> 
> `juil. 03, 2017 11:34:36 PM java.util.prefs.WindowsPreferences <init>
> WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
> Current dir:D:\Developpement\Java\Eclipse\Workspace\Formation\sarf-master
> 
> Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
> 	at org.apache.commons.digester3.Digester.<init>(Digester.java:282)
> 	at sarf.verb.trilateral.augmented.AugmentedTrilateralRootTreeCreator.buildXmlVerbTree(AugmentedTrilateralRootTreeCreator.java:25)
> 	at sarf.DatabaseManager.getAugmentedTrilateralRootTree(DatabaseManager.java:85)
> 	at sarf.SarfDictionary.getAugmentedTrilateralRoot(SarfDictionary.java:37)
> 	at sarf.ui.ControlPaneContainer.processTrilateral(ControlPaneContainer.java:324)
> 	at sarf.ui.ControlPaneContainer.rootEntered(ControlPaneContainer.java:308)
> 	at sarf.ui.ControlPaneContainer.access$4(ControlPaneContainer.java:271)
> 	at sarf.ui.ControlPaneContainer$12.actionPerformed(ControlPaneContainer.java:266)`

I wonder how you made it to succeed in using it ...

Bâraka Allâhu fîka

**Comment by alsaydi** [comment]
Try moving the database folder (db) into the src folder.
